routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware'=>'language'],function ()
{
    Route::get('/', 'PhotoController@index');

    Route::resource('photo', 'PhotoController');
    Route::get('user/{id}','UserController@show')->name('user-show');
    Route::resource('comment', 'CommentController')->except(['index','show','create']);

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('language/{locale}', 'LanguageSwitcherController@switcher')
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Orchid\Attachment\Attachable;
use Orchid\Filters\Filterable;
use Orchid\Screen\AsSource;

class Comment extends Model
{
    use AsSource, Attachable, Filterable;
    protected $fillable = [
        'user_id',
        'photo_id',
        'body',
        'assessment'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function photo()
    {
        return $this->belongsTo(Photo::class);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Http\Requests\CommentReguest;
use App\Photo;
use Illuminate\Http\Request;

class CommentController extends Controller
{

    /**
     * CommentController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param CommentReguest $request
     * @param Photo $photo
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CommentReguest $request)
    {
        $user = $request->user();
        $comment = new Comment();
        $comment->user_id = $user->id;
        $comment->photo_id = $request->input('photo_id');
        $comment->body = $request->input('body');
        $comment->assessment = $request->input('assessment');
        $comment->save();
        return back()->with('status', 'Comment has added');
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit($id)
    {

        $comment = Comment::findOrFail($id);
        $this->authorize('edit',$comment);
        return view('comment.edit',compact('comment'));
    }


    /**
     * @param CommentReguest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(CommentReguest $request, $id)
    {
        $comment = Comment::findOrFail($id);
        $photo_id = $request->input('photo_id');
        $user = $request->user();
        $comment->user_id = $user->id;
        $comment->photo_id = $photo_id;
        $comment->body = $request->input('body');
        $comment->assessment = $request->input('assessment');
        $comment->save();
        return redirect(route('photo.show',$photo_id))->with('status', 'Comment has updated');

    }


    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $comment = Comment::findOrFail($id);
        $this->authorize('delete',$comment);
        $comment->delete();
        return back()->with('status', 'Comment has deleted');
    }
}

resources/views/comment/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 20px;">@lang('messages.update_comment')</h1>
    <form method="post" action="{{route('comment.update',['comment' => $comment])}}">
        @method('put')
        @csrf
        <input type="hidden" name="photo_id" value="{{$comment->photo->id}}">
        <div class="form-group">
            <label for="comment">@lang('messages.enter_comment')</label>
            <textarea name="body" class="form-control @error('body') is-invalid @enderror" id="comment" rows="3">{{$comment->body}}</textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="assessment">@lang('messages.assessment')</label>
            <select name="assessment" id="assessment" class="custom-select  @error('assessment') is-invalid @enderror">
                <option @if($comment->assessment === "1.00") selected @endif value="1">1</option>
                <option @if($comment->assessment === "2.00") selected @endif value="2">2</option>
                <option @if($comment->assessment === "3.00") selected @endif value="3">3</option>
                <option @if($comment->assessment === "4.00") selected @endif value="4">4</option>
                <option @if($comment->assessment === "5.00") selected @endif value="5">5</option>
            </select>
            @error('assessment')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button class="btn-primary" type="submit">@lang('messages.update_comment')</button>
    </form>
    @endsection