routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware'=>'language'],function ()
{
    Route::get('/', 'PhotoController@index');

    Route::resource('photo', 'PhotoController');
    Route::get('user/{id}','UserController@show')->name('user-show');
    Route::resource('comment', 'CommentController')->except(['index','show','create']);

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('language/{locale}', 'LanguageSwitcherController@switcher')
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/User.php
<?php

namespace App;

use Orchid\Platform\Models\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'last_login',
        'permissions',
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'permissions',
        'uses_two_factor_auth',
        'two_factor_secret_code',
        'two_factor_recovery_code',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'permissions'          => 'array',
        'email_verified_at'    => 'datetime',
        'last_login'           => 'datetime',
        'uses_two_factor_auth' => 'boolean',
    ];

    /**
     * The attributes for which you can use filters in url.
     *
     * @var array
     */
    protected $allowedFilters = [
        'id',
        'name',
        'email',
        'permissions',
    ];

    /**
     * The attributes for which can use sort in url.
     *
     * @var array
     */
    protected $allowedSorts = [
        'id',
        'name',
        'email',
        'last_login',
        'updated_at',
        'created_at',
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * UserController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('user.show',compact('user'));

    }
}

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 20px">{{$user->name}}</h1>
    @can('displayCreateButton',$user)
    <button type="button" class="btn btn-outline-success">
        <a class="links" href="{{route('photo.create')}}">@lang('messages.add_photo')</a>
    </button>
    @endcan
    <div class="row">
    @foreach($user->photos as $photo)
        <div style="margin-top: 20px" class="col col-md-4">
            <div class="card" style="width: 18rem;">
                @if($photo->photo !== 'noPhoto.jpg')
                    <img class="card-img-top" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="Photo">
                @else
                    <img src="{{asset('noPhoto.jpg')}}" class="card-img-top" alt="No photo">
                @endif
                <div class="card-body">
                    <h5 class="card-title"><a href="{{route('photo.show',['photo' => $photo])}}">{{$photo->title}}</a></h5>
                    <h5>@lang('messages.author'): {{$photo->user->name}}</h5>
                    <h6>@lang('messages.avg'): {{number_format($photo->comments->avg('assessment'),2)}}</h6>
                    <div class="row">
                        @can('edit',$photo)
                    <button  style="margin-right: 10px" type="button" class="btn btn-outline-success">
                        <a href="{{route('photo.edit',['photo' => $photo->id])}}">@lang('messages.edit')</a>
                    </button>
                        @endcan
                        @can('delete',$photo)
                    <form action="{{route('photo.destroy',['photo' => $photo->id])}}" method="post">
                        @method('delete')
                        @csrf
                        <button type="submit" class="btn btn-danger">@lang('messages.delete')</button>
                    </form>
                            @endcan
                </div>
                </div>
            </div>
        </div>
    @endforeach
    </div>
    @endsection