routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::group(['middleware'=>'language'],function ()
{
    Route::get('/', 'PhotoController@index');

    Route::resource('photo', 'PhotoController');
    Route::get('user/{id}','UserController@show')->name('user-show');
    Route::resource('comment', 'CommentController')->except(['index','show','create']);

    Auth::routes();

    Route::get('/home', 'HomeController@index')->name('home');
});

Route::get('language/{locale}', 'LanguageSwitcherController@switcher')
    ->name('language.switcher')
    ->where('locale', 'en|ru');

app/Photo.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = [
        'user_id',
        'title',
        'photo'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user ()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhotoRequest;
use App\Photo;
use Illuminate\Http\Request;

class PhotoController extends Controller
{
    /**
     * PhotoController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $photos = Photo::paginate(9);
        return view('photo.index',compact('photos'));
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        return view('photo.create');
    }


    /**
     * @param PhotoRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PhotoRequest $request)
    {
        $user = $request->user();
        $photo = new Photo();
        $photo->user_id = $user->id;
        $photo->title = $request->input('title');
        $file = $request->file('photo');
        if (!is_null($file)) {
            $path = $file->store('photo', 'public');
            $photo['photo'] = $path;
        }
        $photo->save();
        return redirect(route('photo.index'))->with('status', "Photo {$photo->title} success added!");
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        $photo = Photo::findOrFail($id);
        return view('photo.show',compact('photo'));
    }


    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit($id)
    {
        $photo = Photo::findOrFail($id);
        $this->authorize('edit',$photo);
        return view('photo.edit',compact('photo'));
    }


    /**
     * @param PhotoRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(PhotoRequest $request, $id)
    {
        $photo = Photo::findOrFail($id);
        $data = $request->all();
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $path = $file->store('photo', 'public');
            $data['photo'] = $path;
        }
        $photo->update($data);
        return redirect(route('photo.index'))->with('status', "Photo {$photo->title} success updated!");
    }


    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy($id)
    {
        $photo = Photo::findOrfail($id);
        $this->authorize('delete',$photo);
        $photo->delete();
        return back()->with('status', "Photo {$photo->title} success deleted!");
    }
}

resources/views/photo/create.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 25px;">@lang('messages.add_photo')</h1>
    <form method="post" action="{{route('photo.store')}}" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="title">@lang('messages.photo_title')</label>
            <input type="text"  class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="customFile" name="photo">
                @error('photo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">@lang('messages.chose_picture')</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">@lang('messages.add_photo')</button>
    </form>
    @endsection

resources/views/photo/edit.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 25px;">@lang('messages.update_photo')</h1>
    <form method="post" action="{{route('photo.update',$photo)}}" enctype="multipart/form-data">
        @method('put')
        @csrf
        <div class="form-group">
            <label for="title">@lang('messages.photo_title')</label>
            <input type="text"  value="{{$photo->title}}" class="form-control @error('title') is-invalid @enderror" id="title" name="title">
            @error('title')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <figure class="figure">
            @if($photo->photo !== 'noPhoto.jpg')
                <img class="figure-img img-fluid rounded" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="photo">
            @else
                <img src="{{asset('noPhoto.jpg')}}" class="figure-img img-fluid rounded" alt="No photo">
            @endif
        </figure>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input @error('photo') is-invalid @enderror" id="customFile" name="photo">
                @error('photo')
                <div class="alert alert-danger">{{ $message }}</div>
                @enderror
                <label class="custom-file-label" for="customFile">@lang('messages.chose_picture')</label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">@lang('messages.update_photo')</button>
    </form>
    @endsection

resources/views/photo/index.blade.php
@extends('layouts.app')
@section('content')
    <h1 style="margin-top: 50px" class="main-title">@lang('messages.all_photo')</h1>
        <div class="row">
            @foreach($photos as $photo)
            <div style="margin-top: 20px" class="col col-md-4">
                <div class="card" style="width: 18rem;">
                    @if($photo->photo !== 'noPhoto.jpg')
                        <img class="card-img-top" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="Photo">
                    @else
                        <img src="{{asset('noPhoto.jpg')}}" class="card-img-top" alt="No photo">
                    @endif
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{route('photo.show',['photo' => $photo])}}">{{$photo->title}}</a></h5>
                        <h5>@lang('messages.author'): <a href="{{route('user-show',$photo->user->id)}}">{{$photo->user->name}}</a></h5>
                        <h6>@lang('messages.avg'): {{number_format($photo->comments->avg('assessment'),2)}}</h6>
                    </div>
                </div>
            </div>
                @endforeach
        </div>
    <div class="row p-5">
        <div class="col-12 offset-4">
            {{ $photos->links() }}
        </div>
    </div>
    @endsection

resources/views/photo/show.blade.php
@extends('layouts.app')
@section('content')
    <h1>{{$photo->title}}</h1>
    @if($photo->photo !== 'noPhoto.jpg')
        <img class="card-img-top" src="{{asset('/storage/' .
                        $photo->photo)}}" alt="Photo">
    @else
        <img src="{{asset('noPhoto.jpg')}}" class="card-img-top" alt="No photo">
    @endif
    <h4>@lang('messages.avg'): {{number_format($photo->comments->avg('assessment'),2)}}</h4>
    <button style="margin-top: 10px;" class="btn btn-primary" type="button" data-toggle="collapse" data-target="#comment{{$photo->id}}" aria-expanded="false" aria-controls="collapseExample">
        @lang('messages.comments')
    </button>
    @foreach($photo->comments as $comment)
        <div class="collapse comment" id="comment{{$photo->id}}">
            <div style="margin-top: 10px" class="card card-body">
                <h4>{{$comment->user->name}}</h4>
                {{$comment->body}}
                <p>@lang('messages.assessment'): {{$comment->assessment}}</p>
                @can('delete',$comment)
                <form  method="post"  action="{{ route('comment.destroy',$comment->id) }}">
                    @method('DELETE')
                    @csrf
                    <button class="like btn-danger" type="submit">@lang('messages.delete')</button>
                </form>
                @endcan
                @can('edit',$comment)
                <a style="width: 100px; margin-top: 5px" class="btn btn-primary" href="{{route('comment.edit',$comment->id)}}">@lang('messages.edit')</a>
                    @endcan
            </div>
        </div>
    @endforeach
    <form method="post" action="{{route('comment.store')}}">
        @csrf
        <input type="hidden" name="photo_id" value="{{$photo->id}}">
        <div class="form-group">
            <label for="comment">@lang('messages.enter_comment')</label>
            <textarea name="body" class="form-control @error('body') is-invalid @enderror" id="comment" rows="3"></textarea>
            @error('body')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="assessment">@lang('messages.assessment')</label>
            <select name="assessment" id="assessment" class="custom-select  @error('assessment') is-invalid @enderror">
                <option selected value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
            @error('assessment')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button style="margin-bottom: 20px;" class="btn-primary" type="submit">@lang('messages.add_comment')</button>
    </form>
    @endsection